{{- include "ark-scraper-collector.validateMailer" . -}}
{{- $mailerNeedsSecret := and .Values.mailer.enabled (not .Values.mailer.api.existingSecret) .Values.mailer.api.apiKey -}}
{{- if $mailerNeedsSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ark-scraper-collector.mailerSecretName" . }}
  labels:
    {{- include "ark-scraper-collector.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mailer.api.apiKey }}
  {{ .Values.mailer.api.apiKeyKey }}: {{ .Values.mailer.api.apiKey | b64enc }}
  {{- end }}
{{- end }}
