{{- include "ark-scraper-collector.validateRabbitmqAuth" . -}}
{{- $rabbitmqNeedsSecret := and (not .Values.rabbitmq.auth.existingSecret) (or .Values.rabbitmq.auth.username .Values.rabbitmq.auth.password) -}}
{{- if $rabbitmqNeedsSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ark-scraper-collector.rabbitmqSecretName" . }}
  labels:
    {{- include "ark-scraper-collector.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.rabbitmq.auth.username }}
  {{ .Values.rabbitmq.auth.usernameKey }}: {{ .Values.rabbitmq.auth.username | b64enc }}
  {{- end }}
  {{- if .Values.rabbitmq.auth.password }}
  {{ .Values.rabbitmq.auth.passwordKey }}: {{ .Values.rabbitmq.auth.password | b64enc }}
  {{- end }}
{{- end }}
