apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-mailer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fastapi-mailer.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "fastapi-mailer.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  type: {{ .Values.service.type }}
