{{- include "ark-scraper.validatePostgresAuth" . -}}
{{- $postgresNeedsSecret := and (not .Values.postgres.auth.existingSecret) (or .Values.postgres.auth.username .Values.postgres.auth.password) -}}
{{- if $postgresNeedsSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ark-scraper.postgresSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ark-scraper.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgres.auth.username }}
  {{ .Values.postgres.auth.usernameKey }}: {{ .Values.postgres.auth.username | b64enc }}
  {{- end }}
  {{- if .Values.postgres.auth.password }}
  {{ .Values.postgres.auth.passwordKey }}: {{ .Values.postgres.auth.password | b64enc }}
  {{- end }}
{{- end }}
